# Generated by Django 5.0.4 on 2024-09-26 04:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='album',
            name='num_stars',
            field=models.IntegerField(choices=[(1, 'wrost'), (2, 'Bad'), (3, 'Average'), (4, 'Good'), (5, 'Best')]),
        ),
    ]
